spring:
  datasource:
    username: root
    password: 6699
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

project:
  poster: poster/

base:
  url: "http://localhost:8080"